---
apiVersion: pkg.crossplane.io/v1
kind: Provider

metadata:
  name: provider-aws
  labels:
    pkg.crossplane.io/provider: provider-aws

spec:
  package: "crossplane/provider-aws:v0.32.0"

...
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig

metadata:
  name: default
  labels:
    pkg.crossplane.io/provider: provider-aws

spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds

...
